// import {
//   Geist,
//   Geist_Mono,
//   Philosopher,
//   Old_Standard_TT,
// } from "next/font/google";

// import "./globals.css";
// import Navbar from "@/component/Navbar";
// import SecondNavbar from "@/component/SecondNaber";
// import Footer from "@/component/Footer";
// import ScrollToTop from "@/component/ScrollToTop";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const philosopher = Philosopher({
//   variable: "--font-philosopher",
//   subsets: ["latin"],
//   weight: ["400"],
//   style: ["normal"],
// });

// const oldStandard = Old_Standard_TT({
//   variable: "--font-old-standard",
//   subsets: ["latin"],
//   weight: ["400"],
//   style: ["normal"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} ${philosopher.variable} ${oldStandard.variable} h-full antialiased`}
//     >
//       <body>
//         <Navbar />
//         <SecondNavbar />

//         {children}

//         <Footer />
//         <ScrollToTop />
//       </body>
//     </html>
//   );
// }




// import {
//   Geist,
//   Geist_Mono,
//   Philosopher,
//   Old_Standard_TT,
//   Great_Vibes,
// } from "next/font/google";

// import "./globals.css";
// import Navbar from "@/component/Navbar";
// import SecondNavbar from "@/component/SecondNaber";
// import Footer from "@/component/Footer";
// import ScrollToTop from "@/component/ScrollToTop";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const philosopher = Philosopher({
//   variable: "--font-philosopher",
//   subsets: ["latin"],
//   weight: ["400"],
//   style: ["normal"],
// });

// const oldStandard = Old_Standard_TT({
//   variable: "--font-old-standard",
//   subsets: ["latin"],
//   weight: ["400"],
//   style: ["normal"],
// });

// const greatVibes = Great_Vibes({
//   variable: "--font-great-vibes",
//   subsets: ["latin"],
//   weight: ["400"],
//   style: ["normal"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`
//         ${geistSans.variable}
//         ${geistMono.variable}
//         ${philosopher.variable}
//         ${oldStandard.variable}
//         ${greatVibes.variable}
//         h-full
//         antialiased
//       `}
//     >
//       <body>
//         <Navbar />
//         <SecondNavbar />

//         {children}

//         <Footer />
//         <ScrollToTop />
//       </body>
//     </html>
//   );
// }





import {
  Geist,
  Geist_Mono,
  Philosopher,
  Old_Standard_TT,
  Great_Vibes,
} from "next/font/google";

import "./globals.css";
import Navbar from "@/component/Navbar";
import SecondNavbar from "@/component/SecondNaber";
import Footer from "@/component/Footer";
import ScrollToTop from "@/component/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const philosopher = Philosopher({
  variable: "--font-philosopher",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
});

const oldStandard = Old_Standard_TT({
  variable: "--font-old-standard",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        ${philosopher.variable}
        ${oldStandard.variable}
        ${greatVibes.variable}
        h-full
        antialiased
      `}
    >
      <body>
        <Navbar />
        <SecondNavbar />

        {children}

        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}